spring:
  application:
    name: spring-code
  profiles:
    active: dev
uploadSetting:
  ACCESS_KEY: LTAI5tNhXKtw2YWe4XYXo4iN
  ACCESS_KEY_SECRET: WjmN8KOFHeLFG3bNb9e6bXsIoBPsXx
server:
  servlet:
    context-path: /api
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true