spring:
  application:
    name: spring-code
  profiles:
    active: dev
uploadSetting:
  ACCESS_KEY: 111111
  ACCESS_KEY_SECRET: 1111
server:
  servlet:
    context-path: /api
  port: 8099
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
