spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    password: 12345678
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost
logging:
  config: classpath:logback-dev.xml